return {
    PlaceObj('ModItemCode', { 'name', "Ranges", 'CodeFileName', "Code/Ranges.lua" }),
    PlaceObj('ModItemOptionChoice', {
        'name', "Preset",
        'DisplayName', "Range preset",
        'Help', "2x, 5x and 10x override every multiplier. Custom uses your saved individual values. Apply to see actual colony ranges.",
        'DefaultValue', "2x",
        'ChoiceList', {"2x", "5x", "10x", "Custom"},
    }),
    PlaceObj('ModItemOptionToggle', {
        'name', "Enabled",
        'DisplayName', "Enable range changes",
        'Help', "Turn off and apply to restore normal ranges before removing this mod. Save afterward. Existing safari routes stay as drawn.",
        'DefaultValue', true,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Domes",
        'DisplayName', "Dome and station range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Outside workplaces, stations, and shared colonist reach checks.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Hubs",
        'DisplayName', "Drone Hub range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Drone Hub service range and slider limit.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Commanders",
        'DisplayName', "RC Commander range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. RC Commanders and drone-controlling variants.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Rockets",
        'DisplayName', "Rocket drone range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. The drone service range of rockets.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Extenders",
        'DisplayName', "Drone Hub Extender range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. The area served by each linked extender.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Scrubbers",
        'DisplayName', "Scrubber range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Dust-cleaning radius and slider limit. Larger radii retain normal power-cost scaling.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Heaters",
        'DisplayName', "Heater range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Heating radius and slider limit. Larger radii retain normal power-cost scaling.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Lasers",
        'DisplayName', "Meteor laser range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Both protection and interception distances. Fire rate stays unchanged.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Extractors",
        'DisplayName', "Extractor deposit range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Reach to compatible underground deposits. Includes compatible modded extractors.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Sensors",
        'DisplayName', "Sensor scanning reach multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Distance over which towers boost sector scanning. Does not change disaster warning time or law effects.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Suns",
        'DisplayName', "Artificial Sun range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Solar-panel illumination and the associated heat radius. Includes compatible modded suns.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Struts",
        'DisplayName', "Underground support range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. The work radius used for cave-in protection.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "SafariSights",
        'DisplayName', "Safari attraction range multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Distance from the route at which tourists can see attractions.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "SafariRoutes",
        'DisplayName', "Safari route length multiplier",
        'Help', "1 = normal, 2 = double, up to 10. Maximum length when editing a safari route. Existing routes are not rewritten.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Forestation",
        'DisplayName', "Forestation Plant range multiplier",
        'Help', "Planting radius. Refreshes the cached planting area.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Mohole",
        'DisplayName', "Mohole heat range multiplier",
        'Help', "Heat radius. Does not change production.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
    PlaceObj('ModItemOptionNumber', {
        'name', "Stirling",
        'DisplayName', "Advanced Stirling heat range multiplier",
        'Help', "Heat radius while open and working.",
        'DefaultValue', 2,
        'MinValue', 1,
        'MaxValue', 10,
        'StepSize', 1,
    }),
}
